name: 'Run shellcheck and shfmt'
description: 'Run shellcheck and shfmt to maintain a consistent codebase.'
author: 'ashthespy'

inputs:
  only_changed:
    description: Flag to only test changed files
    default: 'false'
    required: false
  path:
    description: "See `[path]` of `find`."
    default: '.'
    required: false
  pattern:
    description: "See `-name [pattern]` of `find`."
    default: ''
    required: false
  exclude:
    description: "See `-not -path [exclude]` of `find`."
    required: false
  shellcheck_flags:
    description: "Flags for shellcheck."
    default: '--color=always --external-sources'
    required: false
  shfmt_flags:
    description: "Flags for shfmt."
    default: '-l'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'